### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [AndrewHaluza/zsh-web-open#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Also, please add what dependencies are required by your plugin - macOs doesn't have an `open_command` command, for example.

Thanks!

**Comment by AndrewHaluza** [comment]
It's compatible with ubuntu 20.04, not sure for earlier, but with nice chance is.
